
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { env } from '@/config/env';
import { testDatabaseConnection as robustTestConnection } from '@/utils/db-connection';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Create a fallback client for development when env vars are missing
const supabaseUrl = env.supabaseUrl || 'https://reewcfpjlnufktvahtii.supabase.co';
const supabaseAnonKey = env.supabaseAnonKey || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJlZXdjZnBqbG51Zmt0dmFodGlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIwNzQxNTUsImV4cCI6MjA1NzY1MDE1NX0.nr7hXeKEvsVSi0qvQjb1_0SZz8Lx0JyHRbwTdcrVCcY';

export const supabase = createClient<Database>(supabaseUrl, supabaseAnonKey);

// Helper function to check if Supabase is properly configured
export const isSupabaseConfigured = (): boolean => {
  return !!(env.supabaseUrl && env.supabaseAnonKey && 
           !env.supabaseUrl.includes('placeholder') && 
           !env.supabaseAnonKey.includes('placeholder'));
};

// Helper function to test database connection (re-exporting robust version)
export const testDatabaseConnection = robustTestConnection;